name: basic_sprite_test
description: Project to test Flame's sprite perfomance

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flame: ^1.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: any
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
